<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="sdcm014" name="com.xmd.testcase.login.LoginPage_001_LoginSuccess_Test" tests="2" failures="0" timestamp="3 Aug 2017 08:43:51 GMT" time="37.715" errors="1">
  <testcase name="loginSuccessTest" time="3.800" classname="com.xmd.testcase.login.LoginPage_001_LoginSuccess_Test"/>
  <testcase name="loginSuccessTest" time="33.915" classname="com.xmd.testcase.login.LoginPage_001_LoginSuccess_Test">
    <error type="java.lang.AssertionError" message="超时！！！30秒内未找到元素[By.xpath: /html/body/header/div[2]/span]">
      <![CDATA[java.lang.AssertionError: 超时！！！30秒内未找到元素[By.xpath: /html/body/header/div[2]/span]
	at org.testng.Assert.fail(Assert.java:94)
	at com.xmd.util.SeleniumUtil.waitForElementToLoad(SeleniumUtil.java:42)
	at com.xmd.util.SeleniumUtil.verifyClubTitle(SeleniumUtil.java:84)
	at com.xmd.pages.pagesHelper.LoginPageHelper.verifyLogin(LoginPageHelper.java:42)
	at com.xmd.testcase.login.LoginPage_001_LoginSuccess_Test.loginSuccessTest(LoginPage_001_LoginSuccess_Test.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:38)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:382)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </error>
  </testcase> <!-- loginSuccessTest -->
</testsuite> <!-- com.xmd.testcase.login.LoginPage_001_LoginSuccess_Test -->
